/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";
import './App.css';

export function Home(props) {
  const { nodes, materials } = useGLTF("models/s.gltf");
  
 
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <directionalLight
          name="DirectionalLight"
          intensity={1}
          decay={2}
          position={[-0.745, 14.284, -0.754]}
        >
          <group position={[0, 0, -1]} />
        </directionalLight>
        <directionalLight
          name="DirectionalLight_2"
          intensity={1}
          decay={2}
          position={[-20.07, 12.417, -4.992]}
        >
          <group position={[0, 0, -1]} />
        </directionalLight>
        <group name="setglb">
          <mesh
            name="Ground"
            castShadow
            receiveShadow
            geometry={nodes.Ground.geometry}
            material={materials["Material.002"]}
            position={[-0.017, 0.211, 0]}
            scale={[0.97, 0.188, 1]}
          />
          <mesh
            name="bricks"
            castShadow
            receiveShadow
            geometry={nodes.bricks.geometry}
            material={materials.floor}
            position={[-3.324, 0.308, 0]}
          />
          <mesh
            name="Cube"
            castShadow
            receiveShadow
            geometry={nodes.Cube.geometry}
            material={materials.Material}
            position={[1.378, 1.048, 2.236]}
          />
          <mesh
            name="shelf"
            castShadow
            receiveShadow
            geometry={nodes.shelf.geometry}
            material={materials.shelf}
            position={[1.918, 0.322, 0]}
          />
          <mesh
            name="partition"
            castShadow
            receiveShadow
            geometry={nodes.partition.geometry}
            material={materials.shelf}
            position={[2.337, 2.418, 1.437]}
            scale={[1, 1, 1.192]}
          />
          <mesh
            name="Plane"
            castShadow
            receiveShadow
            geometry={nodes.Plane.geometry}
            material={materials.floor}
            position={[1.372, 2.369, -0.949]}
            scale={[1.351, 1, 2.026]}
          />
          <mesh
            name="Plane043"
            castShadow
            receiveShadow
            geometry={nodes.Plane043.geometry}
            material={materials.Metal}
            position={[0.317, 2.541, -1.4]}
            rotation={[-1.449, -1.527, -1.449]}
            scale={[1.149, 1.138, 1.376]}
          >
            <mesh
              name="Plane044"
              castShadow
              receiveShadow
              geometry={nodes.Plane044.geometry}
              material={materials["Metal.001"]}
            />
            <mesh
              name="Plane082"
              castShadow
              receiveShadow
              geometry={nodes.Plane082.geometry}
              material={materials["Black.003"]}
              position={[0.105, 0.011, -0.039]}
            />
          </mesh>
          <mesh
            name="Cube013"
            castShadow
            receiveShadow
            geometry={nodes.Cube013.geometry}
            material={materials.Steel}
            position={[0.391, 2.509, -0.423]}
            rotation={[0, -0.995, 0]}
            scale={[1.583, 1.606, 1.527]}
          />
          <mesh
            name="Plane054"
            castShadow
            receiveShadow
            geometry={nodes.Plane054.geometry}
            material={materials["White Gloss"]}
            position={[0.83, 2.443, -0.579]}
            rotation={[Math.PI, -1.011, Math.PI]}
            scale={[0.198, 0.201, 0.19]}
          >
            <mesh
              name="Plane055"
              castShadow
              receiveShadow
              geometry={nodes.Plane055.geometry}
              material={materials["White Gloss"]}
              position={[-0.003, 0, 0]}
            />
            <mesh
              name="Plane056"
              castShadow
              receiveShadow
              geometry={nodes.Plane056.geometry}
              material={materials["Black.001"]}
            />
          </mesh>
          <mesh
            name="Plane049"
            castShadow
            receiveShadow
            geometry={nodes.Plane049.geometry}
            material={materials["Wood 3"]}
            position={[1.142, 2.444, 0.13]}
            rotation={[-Math.PI, 0.006, -Math.PI]}
            scale={[1.477, 1.597, 1.614]}
          >
            <mesh
              name="Cube010"
              castShadow
              receiveShadow
              geometry={nodes.Cube010.geometry}
              material={materials["Wood 3"]}
              position={[0, 0.067, -0.18]}
            />
            <mesh
              name="Plane050"
              castShadow
              receiveShadow
              geometry={nodes.Plane050.geometry}
              material={materials["Wood 3"]}
              position={[0, 0.103, -0.18]}
              rotation={[0.369, 0, 0]}
            >
              <mesh
                name="Circle005"
                castShadow
                receiveShadow
                geometry={nodes.Circle005.geometry}
                material={materials["White Gloss"]}
                position={[0, 0.522, 0.001]}
                rotation={[1.683, 0, 0]}
              />
            </mesh>
          </mesh>
          <mesh
            name="Plane004"
            castShadow
            receiveShadow
            geometry={nodes.Plane004.geometry}
            material={materials.Bg}
            position={[1.226, 2.443, -1.456]}
            rotation={[Math.PI, -0.003, Math.PI]}
            scale={[0.21, 0.227, 0.229]}
          />
          <mesh
            name="Plane005"
            castShadow
            receiveShadow
            geometry={nodes.Plane005.geometry}
            material={materials.Bg}
            position={[2.229, 2.443, 0.42]}
            rotation={[Math.PI, -0.003, Math.PI]}
            scale={[0.118, 0.872, 0.129]}
          />
          <mesh
            name="Plane006"
            castShadow
            receiveShadow
            geometry={nodes.Plane006.geometry}
            material={materials.Bg}
            position={[2.435, 2.129, -1.798]}
            rotation={[Math.PI, -0.003, Math.PI]}
            scale={[0.118, 0.094, 0.288]}
          />
          <mesh
            name="Plane007"
            castShadow
            receiveShadow
            geometry={nodes.Plane007.geometry}
            material={materials.Bg}
            position={[1.133, 2.443, -2.539]}
            rotation={[Math.PI, -0.003, Math.PI]}
            scale={[0.118, 0.048, 0.121]}
          />
          <mesh
            name="Plane001"
            castShadow
            receiveShadow
            geometry={nodes.Plane001.geometry}
            material={materials.shelf}
            position={[2.431, 3.859, -0.948]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.333, -0.811, -2.061]}
          />
          <mesh
            name="Plane009"
            castShadow
            receiveShadow
            geometry={nodes.Plane009.geometry}
            material={materials.shelf}
            position={[2.431, 3.538, 2.233]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.333, -0.811, -0.784]}
          />
          <mesh
            name="Plane010"
            castShadow
            receiveShadow
            geometry={nodes.Plane010.geometry}
            material={materials.shelf}
            position={[2.431, 2.494, 2.233]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.333, -0.811, -0.784]}
          />
          <mesh
            name="Cube001"
            castShadow
            receiveShadow
            geometry={nodes.Cube001.geometry}
            material={materials.inner}
            position={[2.547, 4.4, -2.825]}
            rotation={[0, -1.558, 0]}
            scale={[1.149, 1, 1]}
          />
          <mesh
            name="Cube002"
            castShadow
            receiveShadow
            geometry={nodes.Cube002.geometry}
            material={materials.book1}
            position={[2.553, 4.405, -2.825]}
            rotation={[0, -1.558, 0]}
            scale={[1.149, 1, 1]}
          />
          <mesh
            name="Cube003"
            castShadow
            receiveShadow
            geometry={nodes.Cube003.geometry}
            material={materials.inner}
            position={[2.547, 4.303, -2.541]}
            rotation={[0, -1.558, 0]}
          />
          <mesh
            name="Cube004"
            castShadow
            receiveShadow
            geometry={nodes.Cube004.geometry}
            material={materials.book2}
            position={[2.553, 4.307, -2.541]}
            rotation={[0, -1.558, 0]}
          />
          <mesh
            name="Cube005"
            castShadow
            receiveShadow
            geometry={nodes.Cube005.geometry}
            material={materials.inner}
            position={[2.547, 4.303, -2.288]}
            rotation={[0, -1.558, 0]}
            scale={[0.222, 0.338, 0.28]}
          />
          <mesh
            name="Cube006"
            castShadow
            receiveShadow
            geometry={nodes.Cube006.geometry}
            material={materials.book3}
            position={[2.553, 4.307, -2.288]}
            rotation={[0, -1.558, 0]}
            scale={[0.222, 0.402, 0.317]}
          />
          <mesh
            name="Cube007"
            castShadow
            receiveShadow
            geometry={nodes.Cube007.geometry}
            material={materials.inner}
            position={[2.547, 4.391, -2.021]}
            rotation={[0, -1.558, 0]}
            scale={[0.237, 0.449, 0.28]}
          />
          <mesh
            name="Cube008"
            castShadow
            receiveShadow
            geometry={nodes.Cube008.geometry}
            material={materials.book4}
            position={[2.553, 4.396, -2.021]}
            rotation={[0, -1.558, 0]}
            scale={[0.237, 0.534, 0.317]}
          />
          <mesh
            name="Cube009"
            castShadow
            receiveShadow
            geometry={nodes.Cube009.geometry}
            material={materials.inner}
            position={[2.547, 4.303, -1.768]}
            rotation={[0, -1.558, 0]}
            scale={[0.222, 0.338, 0.28]}
          />
          <mesh
            name="Cube011"
            castShadow
            receiveShadow
            geometry={nodes.Cube011.geometry}
            material={materials.book5}
            position={[2.553, 4.307, -1.768]}
            rotation={[0, -1.558, 0]}
            scale={[0.222, 0.402, 0.317]}
          />
          <mesh
            name="Cube012"
            castShadow
            receiveShadow
            geometry={nodes.Cube012.geometry}
            material={materials.inner}
            position={[2.547, 4.303, -1.531]}
            rotation={[0, -1.558, 0]}
            scale={[0.222, 0.338, 0.28]}
          />
          <mesh
            name="Cube014"
            castShadow
            receiveShadow
            geometry={nodes.Cube014.geometry}
            material={materials.book1}
            position={[2.553, 4.307, -1.531]}
            rotation={[0, -1.558, 0]}
            scale={[0.222, 0.402, 0.317]}
          />
          <mesh
            name="Cube015"
            castShadow
            receiveShadow
            geometry={nodes.Cube015.geometry}
            material={materials.inner}
            position={[2.547, 4.303, -1.278]}
            rotation={[0, -1.558, 0]}
            scale={[0.222, 0.338, 0.28]}
          />
          <mesh
            name="Cube016"
            castShadow
            receiveShadow
            geometry={nodes.Cube016.geometry}
            material={materials.book3}
            position={[2.553, 4.307, -1.278]}
            rotation={[0, -1.558, 0]}
            scale={[0.222, 0.402, 0.317]}
          />
          <mesh
            name="Cube017"
            castShadow
            receiveShadow
            geometry={nodes.Cube017.geometry}
            material={materials.inner}
            position={[2.547, 4.303, -0.849]}
            rotation={[-0.527, -1.558, 0.012]}
            scale={[1.021, 1.007, 1]}
          />
          <mesh
            name="Cube018"
            castShadow
            receiveShadow
            geometry={nodes.Cube018.geometry}
            material={materials.book2}
            position={[2.553, 4.307, -0.851]}
            rotation={[-0.527, -1.558, 0.012]}
            scale={[1.117, 1.042, 1]}
          />
          <mesh
            name="Cube019"
            castShadow
            receiveShadow
            geometry={nodes.Cube019.geometry}
            material={materials.inner}
            position={[2.547, 4.085, 0.265]}
            rotation={[-1.685, -1.506, -0.13]}
            scale={[0.222, 0.338, 0.28]}
          />
          <mesh
            name="Cube020"
            castShadow
            receiveShadow
            geometry={nodes.Cube020.geometry}
            material={materials.book2}
            position={[2.553, 4.085, 0.261]}
            rotation={[-1.685, -1.506, -0.13]}
            scale={[0.222, 0.402, 0.317]}
          />
          <mesh
            name="Cube021"
            castShadow
            receiveShadow
            geometry={nodes.Cube021.geometry}
            material={materials.inner}
            position={[2.341, 4.344, 0.267]}
            rotation={[-0.096, -0.831, 1.484]}
            scale={[0.222, 0.338, 0.28]}
          />
          <mesh
            name="Cube022"
            castShadow
            receiveShadow
            geometry={nodes.Cube022.geometry}
            material={materials.book1}
            position={[2.343, 4.344, 0.26]}
            rotation={[-0.096, -0.831, 1.484]}
            scale={[0.222, 0.402, 0.317]}
          />
          <mesh
            name="Cube023"
            castShadow
            receiveShadow
            geometry={nodes.Cube023.geometry}
            material={materials.inner}
            position={[2.548, 2.886, 1.563]}
            rotation={[0, -1.558, 0]}
            scale={[0.151, 0.295, 0.191]}
          />
          <mesh
            name="Cube024"
            castShadow
            receiveShadow
            geometry={nodes.Cube024.geometry}
            material={materials.book1}
            position={[2.552, 2.89, 1.563]}
            rotation={[0, -1.558, 0]}
            scale={[0.151, 0.351, 0.216]}
          />
          <mesh
            name="Cube025"
            castShadow
            receiveShadow
            geometry={nodes.Cube025.geometry}
            material={materials.inner}
            position={[2.548, 2.82, 1.749]}
            rotation={[0, -1.558, 0]}
            scale={[0.151, 0.231, 0.191]}
          />
          <mesh
            name="Cube026"
            castShadow
            receiveShadow
            geometry={nodes.Cube026.geometry}
            material={materials.book5}
            position={[2.552, 2.823, 1.749]}
            rotation={[0, -1.558, 0]}
            scale={[0.151, 0.274, 0.216]}
          />
          <mesh
            name="Cube027"
            castShadow
            receiveShadow
            geometry={nodes.Cube027.geometry}
            material={materials.inner}
            position={[2.341, 2.674, 2.344]}
            rotation={[-0.096, -0.831, 1.484]}
            scale={[0.176, 0.269, 0.223]}
          />
          <mesh
            name="Cube028"
            castShadow
            receiveShadow
            geometry={nodes.Cube028.geometry}
            material={materials.book2}
            position={[2.342, 2.674, 2.338]}
            rotation={[-0.096, -0.831, 1.484]}
            scale={[0.176, 0.32, 0.252]}
          />
          <group
            name="Icosphere"
            position={[1.916, 2.089, 2.239]}
            scale={0.361}
          >
            <mesh
              name="Icosphere001"
              castShadow
              receiveShadow
              geometry={nodes.Icosphere001.geometry}
              material={materials.white}
            />
            <mesh
              name="Icosphere001_1"
              castShadow
              receiveShadow
              geometry={nodes.Icosphere001_1.geometry}
              material={materials.black}
            />
          </group>
          <mesh
            name="Cube029"
            castShadow
            receiveShadow
            geometry={nodes.Cube029.geometry}
            material={materials.chair}

            position={[-1.364, 2.325, -1.193]}
            rotation={[Math.PI, -1.554, Math.PI]}
          />
          <mesh
            name="Cylinder"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder.geometry}
            material={materials.steel}
            position={[-1.382, 1.403, -1.204]}
            rotation={[Math.PI, -1.554, Math.PI]}
            scale={[0.112, 0.094, 0.112]}
          />
          <mesh
            name="Plant001"
            castShadow
            receiveShadow
            geometry={nodes.Plant001.geometry}
            material={materials["Bg.001"]}
            position={[1.922, 2.53, -2.558]}
            rotation={[-1.432, 1.507, 1.423]}
            scale={1.052}
          >
            <mesh
              name="Vert002"
              castShadow
              receiveShadow
              geometry={nodes.Vert002.geometry}
              material={materials["Bg.001"]}
              position={[0, 0.232, 0]}
              rotation={[0, 0.089, 0]}
              scale={1.5}
            >
              <mesh
                name="Plane019"
                castShadow
                receiveShadow
                geometry={nodes.Plane019.geometry}
                material={materials.green}
                position={[0.004, 0.522, 0]}
              />
            </mesh>
          </mesh>
          <mesh
            name="Cube031"
            castShadow
            receiveShadow
            geometry={nodes.Cube031.geometry}
            material={materials["Wood 3.001"]}
            position={[0, 0.067, -0.18]}
          />
          <group
            name="Sketchfab_model"
            position={[-2.536, 0.28, 1.921]}
            rotation={[-Math.PI / 2, 0, -0.487]}
            scale={4.149}
          >
            <group
              name="33f450e3664b4d59a2e706b43cdbe9f0fbx"
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.1}
            >
              <group name="RootNode">
                <group
                  name="Box014"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={0.01}
                >
                  <group name="Object_4" position={[0, -51.672, 0]}>
                    <mesh
                      name="Box014_FA_004_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Box014_FA_004_0.geometry}
                      material={materials.FA_004}
                    />
                    <mesh
                      name="Box014_FA_005_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Box014_FA_005_0.geometry}
                      material={materials.FA_005}
                    />
                    <mesh
                      name="Box014_FA_005_0001"
                      castShadow
                      receiveShadow
                      geometry={nodes.Box014_FA_005_0001.geometry}
                      material={materials.FA_005_0}
                    />
                    <mesh
                      name="Box014_FA_012_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Box014_FA_012_0.geometry}
                      material={materials.FA_012}
                    />
                    <mesh
                      name="Box014_FA_014_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Box014_FA_014_0.geometry}
                      material={materials.FA_014}
                    />
                  </group>
                </group>
                <group
                  name="Line002"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={0.01}
                >
                  <group
                    name="Object_11"
                    position={[-161.602, -197.087, 50.843]}
                  >
                    <mesh
                      name="Line002_Ash_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Line002_Ash_0.geometry}
                      material={materials.material}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
          <group
            name="Sketchfab_model001"
            position={[2.493, 4.507, 2.327]}
            rotation={[-Math.PI / 2, 0, -1.389]}
            scale={0.912}
          >
            <group
              name="Collada_visual_scene_group"
              rotation={[Math.PI / 2, 0, 0]}
            >
              <group name="mesh2a_low">
                <mesh
                  name="defaultMaterial"
                  castShadow
                  receiveShadow
                  geometry={nodes.defaultMaterial.geometry}
                  material={materials.DefaultMaterial}
                  position={[-0.204, 0, 0.172]}
                  rotation={[0, -0.469, 0]}
                  scale={0.905}
                />
              </group>
            </group>
          </group>
          <mesh
            name="Plane008"
            castShadow
            receiveShadow
            geometry={nodes.Plane008.geometry}
            material={materials["metal.001"]}
            position={[1.354, 2.693, -1.457]}
            rotation={[Math.PI, -0.017, Math.PI]}
            scale={[0.255, 0.319, 0.255]}
          >
            <group name="Plane011" position={[0.927, 3.036, 0]}>
              <mesh
                name="Plane011_1"
                castShadow
                receiveShadow
                geometry={nodes.Plane011_1.geometry}
                material={materials["metal.001"]}
              />
              <mesh
                name="Plane011_2"
                castShadow
                receiveShadow
                geometry={nodes.Plane011_2.geometry}
                material={materials["screen.001"]}
              />
            </group>
          </mesh>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/s.gltf");